# Generated by Django 6.0.4 on 2026-04-25 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)])),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('state', models.CharField(choices=[('DF', 'DRAFT'), ('AC', 'ACTIVE'), ('IN', 'INACTIVE')], default='DF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ClasssSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_section', to='teacher.teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couser_section', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_section_enrolled', to='course.classssection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_studen_enrolled', to='student.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='classssection',
            constraint=models.UniqueConstraint(fields=('course', 'teacher'), name='unique_course_teacher'),
        ),
        migrations.AddConstraint(
            model_name='enrolled',
            constraint=models.UniqueConstraint(fields=('student', 'class_section'), name='enroll_class_section'),
        ),
    ]
