# Generated by Django 6.0.4 on 2026-04-23 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)])),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('state', models.CharField(choices=[('DF', 'DRAFT'), ('AC', 'ACTIVE'), ('IN', 'INACTIVE')], default='DF', max_length=2)),
            ],
        ),
    ]
