# Generated by Django 6.0.4 on 2026-04-23 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
