# Generated by Django 6.0.4 on 2026-04-25 01:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0002_alter_student_birth_day'),
        ('teacher', '0002_alter_teacher_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classssection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course'),
        ),
        migrations.AlterField(
            model_name='classssection',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.classssection'),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('enrolled', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='course.enrolled')),
            ],
        ),
    ]
