# Generated by Django 6.0.4 on 2026-04-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_classssection_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
