# Generated by Django 6.0.4 on 2026-04-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_code'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasssSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couser_section', to='course.course')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_section', to='student.student')),
            ],
        ),
    ]
