# Generated by Django 6.0.4 on 2026-04-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_grade'),
        ('teacher', '0002_alter_teacher_birth_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClasssSection',
            new_name='ClassSection',
        ),
    ]
