# Generated by Django 6.0.4 on 2026-04-24 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_classssection'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='classssection',
            name='teacher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_section', to='teacher.teacher'),
        ),
        migrations.AddConstraint(
            model_name='classssection',
            constraint=models.UniqueConstraint(fields=('course_id', 'teacher_id'), name='unique_course_teacher'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='class_section_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_section_enrolled', to='course.classssection'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_studen_enrolled', to='student.student'),
        ),
        migrations.AddConstraint(
            model_name='enrolled',
            constraint=models.UniqueConstraint(fields=('student_id', 'class_section_id'), name='enroll_class_section'),
        ),
    ]
