# Generated by Django 6.0.4 on 2026-04-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_classssection_classsection'),
        ('student', '0002_alter_student_birth_day'),
        ('teacher', '0002_alter_teacher_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='course.course'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sections', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_section_enrollments', to='course.classsection'),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='student.student'),
        ),
    ]
