# Generated by Django 6.0.4 on 2026-04-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_enrolled_alter_classssection_teacher_id_and_more'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classssection',
            name='unique_course_teacher',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='class_section_id',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='student_id',
        ),
        migrations.AddField(
            model_name='classssection',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='couser_section', to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classssection',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_section', to='teacher.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='class_section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='class_section_enrolled', to='course.classssection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolled',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='section_studen_enrolled', to='student.student'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='classssection',
            constraint=models.UniqueConstraint(fields=('course', 'teacher'), name='unique_course_teacher'),
        ),
        migrations.RemoveField(
            model_name='classssection',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='classssection',
            name='teacher_id',
        ),
    ]
