# Generated by Django 6.0.4 on 2026-04-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_classssection_classsection'),
        ('score', '0002_alter_score_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='course.enrolled'),
        ),
    ]
