# Generated by Django 6.0.4 on 2026-04-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.DateField(verbose_name='BirthDay'),
        ),
    ]
